# Generated by Django 2.2.10 on 2020-05-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=200)),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Fp.kindpng.com%2Fpicc%2Fs%2F79-798754_hoteles-y-centros-vacacionales-dish-placeholder-hd-png.png&imgrefurl=https%3A%2F%2Fwww.kindpng.com%2Fimgv%2FiihmoJi_alt-text-placeholder-convenience-food-hd-png-download%2F&tbnid=r4MyYWa6UxepTM&vet=12ahUKEwj6o56e8pHpAhXn6HMBHXXGDW8QMygAegUIARDaAQ..i&docid=DE59x2KNdrhkvM&w=280&h=280&q=placeholder%20food%20images&ved=2ahUKEwj6o56e8pHpAhXn6HMBHXXGDW8QMygAegUIARDaAQ', max_length=3000)),
            ],
        ),
    ]
